#
# Project : TamerCAD
# Module  : Gradle
# File    : gradle.properties
# Version : 0.0.1
#

# JVM
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Enable AndroidX
android.useAndroidX=true

# Kotlin Style
kotlin.code.style=official

# Faster Builds
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Android
android.nonTransitiveRClass=true

# Kotlin
kotlin.incremental=true

# Jetpack Compose
android.defaults.buildfeatures.buildconfig=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Yerel Build Sorununu Çözen Kritik Ayar:
# Gradle'ın Java 25 yerine Java 21 (veya 17) kullanmasını sağlar.
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
