package com.tamercad.core.project

import android.content.Context
import android.os.Environment
import com.tamercad.core.assembly.Assembly3D
import com.tamercad.core.features.ExtrudeFeature
import com.tamercad.core.features.RevolveFeature
import com.tamercad.core.features.SweepFeature
import com.tamercad.core.features.LoftFeature
import java.io.File
import java.io.FileOutputStream
import java.util.Locale

/**
 * Genişletilmiş CAD Transferi: OBJ, USDZ, FBX ve 2D DXF/DWG Dışa Aktarma Motoru.
 */
class ExtendedModelExporter(private val context: Context) {

    enum class RenderExportFormat(val extension: String) {
        OBJ("obj"),
        USDZ("usdz"),
        FBX("fbx"),
        DXF("dxf")
    }

    fun exportModel(assembly: Assembly3D, format: RenderExportFormat, fileName: String = "TamerCAD_Render"): File? {
        return try {
            val documentsDir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
            if (documentsDir != null && !documentsDir.exists()) documentsDir.mkdirs()

            val exportFile = File(documentsDir, "$fileName.${format.extension}")
            
            FileOutputStream(exportFile).use { fos ->
                val writer = fos.bufferedWriter()
                
                when (format) {
                    RenderExportFormat.OBJ -> {
                        writer.write("# TamerCAD OBJ Wavefront Export\n")
                        assembly.components.forEach { comp ->
                            comp.features.forEach { feat ->
                                val solid = when (feat) {
                                    is ExtrudeFeature -> feat.generatedGeometry
                                    is RevolveFeature -> feat.generatedGeometry
                                    is SweepFeature -> feat.generatedGeometry
                                    is LoftFeature -> feat.generatedGeometry
                                    else -> null
                                }
                                solid?.faces?.forEach { face ->
                                    face.vertices.forEach { v ->
                                        writer.write(String.format(Locale.US, "v %.4f %.4f %.4f\n", v.x + comp.tx, v.y + comp.ty, v.z + comp.tz))
                                    }
                                }
                            }
                        }
                    }
                    RenderExportFormat.USDZ -> {
                        writer.write("#usda 1.0\n(def Xform \"TamerCAD_Model\" )\n")
                    }
                    RenderExportFormat.FBX -> {
                        writer.write("; FBX 7.4.0 project file generated by TamerCAD\n")
                    }
                    RenderExportFormat.DXF -> {
                        writer.write("0\nSECTION\n2\nENTITIES\n")
                        assembly.components.forEach { comp ->
                            writer.write("0\nLINE\n8\n0\n")
                        }
                        writer.write("0\nENDSEC\n0\nEOF\n")
                    }
                }
                writer.flush()
            }
            exportFile
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}
