package com.tamercad.ui

enum class CadMode {
    NAVIGATE, SMART_SKETCH, SKETCH_LINE_MANUAL, SKETCH_ARC,
    SKETCH_SPLINE_FIT, SKETCH_SPLINE_CTRL,
    SKETCH_RECT_CENTER, SKETCH_RECT_DIAG, SKETCH_RECT_3PT,
    SKETCH_ELLIPSE, SKETCH_POLYGON, OFFSET_EDGE, TRIM, DELETE,
    MOVE_ROTATE, MIRROR, PATTERN_LINEAR, PROJECT, TEXT,
    EXTRUDE, BOOLEAN, FILLET, SELECT
}
